[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/v1/health"
healthcheckTimeout = 300
numReplicas = 1
sleepApplication = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
